version: '3'

services:
  frontend:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - db-data:/data/db
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
