services:
  frontend:
    build: ./app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build: ./api
    ports:
      - "3000:8080"
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_database=travel_diary

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data:
