version: '3.7'

services:
  frontend:
    build: ./app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - API_BASE_URL=${API_BASE_URL}

  backend:
    build: ./api
    ports:
      - "5000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb
    environment:
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - MONGO_DATABASE=travel_diary
      - ACCESS_SECRET_KEY=${ACCESS_SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}

  mongodb:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data:
